spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
      cluster.port: 9300
app:
  profile: dev #DEVELOP|TEST|PRODUCT